# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM ghcr.io/astral-sh/uv:alpine

# Set working directory
WORKDIR /app

# Copy dependency files
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN uv sync

# Copy project
COPY . .

# Default command
CMD ["uv", "run", "main.py"]
